### ISSUE TITLE
urllib3 connection error 

### ISSUE THREAD

**Issue by natcapresearch** [geopandas/contextily#187]
I am suddenly having issues with base maps timing out. Nothing has changed in my code but this is now happening from home and the office (so, not a location thing). Odd, any ideas? Have you seen this?

````
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a.basemaps.cartocdn.com', port=443): Max retries exceeded with url: /light_all/14/8250/5410.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dd93c6850>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/app.py", line 38, in <module>
    landcoverMap(report, reportData)
  File "/home/jamie/reportgeneration/code/maps/landcover.py", line 8, in landcoverMap
    map1.addBasemap(None)
  File "/home/jamie/reportgeneration/code/map.py", line 64, in addBasemap
    cx.add_basemap(ax, source=baseimage, crs="EPSG:27700", zorder=1, alpha=1, attribution_size=2)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/contextily/plotting.py", line 143, in add_basemap
    image, extent = bounds2img(
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/contextily/tile.py", line 248, in bounds2img
    image = _fetch_tile(tile_url, wait, max_retries)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/contextily/tile.py", line 303, in _fetch_tile
    request = _retryer(tile_url, wait, max_retries)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/contextily/tile.py", line 446, in _retryer
    request = requests.get(tile_url, headers={"user-agent": USER_AGENT})
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/jamie/reportgeneration/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='a.basemaps.cartocdn.com', port=443): Max retries exceeded with url: /light_all/14/8250/5410.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7dd93c6850>: Failed to establish a new connection: [Errno 110] Connection timed out'))
````

**Comment by natcapresearch** [comment]
It looks like an issue with the fastly cdn, now and again it works for me but it is very rare.

**Comment by darribas** [comment]
Thanks for reporting @natcapresearch. As I understand, that is related to the provider rather than `contextily`. It might be worth to track availability over at [`xyzservices`](https://github.com/geopandas/xyzservices)? I'm closing for now but feel free to open another issue over there.
